common_variables = [
    "LMAM_HC20?-_NDXSDI16-_PV",
    "LMAM_HC20?-_NDXSDI8--_PV",
    "LMAM_HC20?A_NDDT01---_TDI",
    "LMAM_HC20?A_NDPT01---_TPI",
    "LMAM_HC20?A_NDXRPI1--_PV",
    "LMAM_HC20?A_WPFT01---_TFI",
    "LMAM_HC20?A_WPXRFI1--_PV",
    "LMAM_HC20?B_NDDT01---_TDI",
    "LMAM_HC20?B_NDFT01---_TFI",
    "LMAM_HC20?B_NDPT01---_TPI",
    "LMAM_HC20?B_NDXRDI1--_PV",
    "LMAM_HC20?B_NDXRFI1--_PV",
    "LMAM_HC20?B_NDXRPI1--_PV",
    "LMAM_HC20?B_WPFT01---_TFI",
    "LMAM_HC20?B_WPXRFI1--_PV",
    "LMAM_HC2?2A_NDDT01---_TDI",
    "LMAM_HC2?2A_NDFT01---_TFI",
    "LMAM_HC2?2A_NDPT01---_TPI",
    "LMAM_HC2?2A_NDXRDI1--_PV",
    "LMAM_HC2?2A_NDXRFI1--_PV",
    "LMAM_HC2?2A_NDXRPI1--_PV",
    "LMAM_HC2?2A_WPFT01---_TFI",
    "LMAM_HC2?2A_WPXRFI1--_PV",
    "LMAM_HC2?2B_NDDT01---_TDI",
    "LMAM_HC2?2B_NDFT01---_TFI",
    "LMAM_HC2?2B_NDPT01---_TPI",
    "LMAM_HC2?2B_NDXRPI1--_PV",
    "LMAM_HC2?2B_PL-------_TPS",
    "LMAM_HC2?2B_PLDT01---_TDI",
    "LMAM_HC2?2B_PLKL90---_TPG",
    "LMAM_HC2?2B_WL-------_TAN",
    "LMAM_HC2?2B_WPXRFI1--_PV",
    "LMAM_HC251B_NDDT01---_TDI",
    "LMAM_HC251B_NDFT01---_TFI",
    "LMAM_HC251B_NDXSDI8--_PV",
    "LMAM_HC251C_NDDT01---_TDI",
    "LMAM_HC251C_NDFT01---_TFI",
    "LMAM_HC251C_NDPT01---_TPI",
    "LMAM_HC251C_NDXRDI1--_PV",
    "LMAM_HC251C_NDXRFI1--_PV",
    "LMAM_HC251C_NDXRPI1--_PV",
    "LMAM_HC251C_WPFT01---_TFI",
    "LMAM_HC251C_WPXRFI1--_PV",
    "LMAM_K2?1--_NDXSDI8--_PV",
    "LMAM_K2?1--_PLDT01---_TDI",
    "LMAM_K2?1--_PPSKN01--_TLI",
    "LMAM_K2?1--_WPFT01---_TFI",
    "LMAM_K2?1--_WPXRFI1--_PV",
    "LMAM_MF20?-_NDXSLI8--_PV",
    "LMAM_MF21?-_NDXSLI8--_PV",
    "LMAM_MK2?2-_---------_EPX",
    "LMAM_MK2?2-_WPFT01---_TFI",
    "LMAM_MK2?2-_WPXRFI1--_PV",
    "LMAM_MP2?1-_---------_EPX",
    "LMAM_MP2?1-_RDXRFI1--_PV",
    "LMAM_MP2?1-_RDXRFI2--_PV",
    "LMAM_MP2?1-_WLEQ01---_TDI",
    "LMAM_MP2?1-_WPFT01---_TFI",
    "LMAM_MP2?1-_WPXRFI2--_PV",
    "LMAM_PM20?A_---------_EPX",
    "LMAM_PM20?A_---------_TNI",
    "LMAM_PM20?B_---------_EPX",
    "LMAM_PM20?B_---------_TNI_ERPM",
    "LMAM_PM20?B_--FAL1---_EI3",
    "LMAM_PM20?B_--FAL1---_TNI_ERPM",
    "LMAM_PM20?B_--FAL2---_EI3",
    "LMAM_PM20?B_--FAL2---_TNI_ERPM",
    "LMAM_PM2?1A_---------_EPX",
    "LMAM_PM2?1B_---------_EPX",
    "LMAM_PM2?2A_---------_EPX",
    "LMAM_PM2?2A_---------_TNI",
    "LMAM_PM2?2A_--FAL1---_EI3",
    "LMAM_PM2?2A_--FAL1---_TNI_ERPM",
    "LMAM_PM2?2A_--FAL2---_EI3",
    "LMAM_PM2?2A_--FAL2---_TNI_ERPM",
    "LMAM_PM2?2B_---------_EPX",
    "LMAM_PM2?2B_---------_TNI",
    "LMAM_PM251B_---------_EPX",
    "LMAM_PM251C_---------_EPX",
    "LMAM_PM251C_--FAL1---_EI3",
    "LMAM_PM251C_--FAL1---_TNI_ERPM",
    "LMAM_PM251C_--FAL2---_EI3",
    "LMAM_PM251C_--FAL2---_TNI_ERPM",
    "LMAM_RZM20?_NDLT01---_TLI",
    "LMAM_RZM20?_NDXRLI1--_PV",
    "LMAM_RZM20?_NDXSLI16-_PV",
    "LMAM_RZM20?_NDXSLI8--_PV",
    "LMAM_RZM20?_WPFT01---_TFI",
    "LMAM_RZM20?_WPXRFI1--_PV",
    "LMAM_RZM2?1_NDLT01---_TLI",
    "LMAM_RZM2?1_NDXSLI16-_PV",
    "LMAM_RZM2?1_NDXSLI8--_PV",
    "LMAM_RZM2?1_OPPDO1---_TFI",
    "LMAM_RZM2?1_OPXRFI2--_PV",
    "LMAM_RZM2?1_OZPDO1---_TFI",
    "LMAM_RZM2?1_OZXRFI1--_PV",
    "LMAM_RZM2?2_NDLT01---_TLI",
    "LMAM_RZM2?2_NDXRLI1--_PV",
    "LMAM_RZM2?2_NDXSLI16-_PV",
    "LMAM_RZM2?2_NDXSLI8--_PV",
    "LMAM_RZM2?2_WPFT01---_TFI",
    "LMAM_RZM2?2_WPXRFI1--_PV",
    "LMAM_RZM251_NDLT01---_TLI",
    "LMAM_RZM251_NDXRLI1--_PV",
    "LMAM_RZM251_WPFT01---_TFI",
    "LMAM_RZM251_WPXRFI1--_PV",
    "LMAM_TM2?1-_---------_EPX",
    "LMAM_TM2?1-_RDFQ01---_TFI",
    "LMAM_TM2?2-_---------_EPX",
    "LMAM_TM2?3-_---------_EPX",
    "LMAY_WM22?2_--FAL----_CVF",
    "LMAY_WM22?3_--FAL----_CVF",
    "LMAY_WM32?2_--FAL----_CVF",
    "LMAY_WM?2?3_--FAL----_CVF"
]


def find_common_variables_for_section_number(section_number: int):
    section_variables = []
    for variable in common_variables:
        descriminator = '?'
        if descriminator in variable:
            new_variable = variable.replace(descriminator, str(section_number))
            section_variables.append(new_variable)
        else:
            section_variables.append(variable)
    return section_variables


if __name__ == '__main__':
    find_common_variables_for_section_number(1)
